FROM node:24-alpine3.23

WORKDIR /app

#For now leave this uncommented, uncomment if we need git. RUN apk update && apt add bash git
RUN apk update && apk --no-cache add bash

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
#Exposing our react dev port
EXPOSE 5173

ENTRYPOINT ["/entrypoint.sh"]