FROM python:3.13.12-slim-trixie

# Install ODBC dependencies
RUN apt-get update && apt-get install -y \
    unixodbc \
    unixodbc-dev \
    odbc-postgresql \
    wget \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

# Set working directory to app directory (optional)
WORKDIR /app

# Copy Python dependencies first
COPY requirements.in .
RUN pip install --no-cache-dir -r requirements.in

# Copy app folder
COPY . /app/backend

EXPOSE 8000

# Start Uvicorn pointing to the app package
CMD ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]